---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 15586.
--- DateTime: 2026/9/21 19:23

---获取传的参数key
local key = KEYS[1]
---获取传的参数count，要扣减的数量
local count=tonumber(ARGV[1])
---获取库存
local stock = tonumber(redis.call("get", key))
---判断库存是否够减
if stock < count then
    return -1
end
---扣减库存
redis.call("decrby", key, count)
--- 再次查询库存
local new_stock=tonumber(redis.call("get", key))
---判断库存是否大于0，防止并发问题
if new_stock < 0 then
    redis.call("incrby", key, count)
    return -1;
end

return 1

