---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 15586.
--- DateTime: 2026/9/21 20:07
---

---获取参数key
local key = KEYS[1]
---获取参数count，需要回滚的数量
local count = tonumber(ARGV[1])

---回滚库存
local new_stock = redis.call("incrby",key,count)

return new_stock